name: Go
on:
  pull_request:
    paths:
      - 'basic-service/**'  
    branches:
      - "*"
    types:
      - opened
      - edited

jobs:
  deploy:
    if: github.event.pull_request.edited == true
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4

    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./basic-service
        tags: sharadregoti/basic-service:${{ github.event.number }}-pr
        file: ./basic-service/Dockerfile

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: "Application can be accessed at this url: http://${{ github.event.number }}.-pr3.7.100.88.sslip.io:4080"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade ${{ github.event.number }}-pr ./basic-service/deployment/basic-service --install --wait --atomic --set=branch_name=${{ github.event.number }}-pr
        kubeconfig: '${{ secrets.KUBE_CONFIG }}'