name: Go
on:
  pull_request:
    paths:
      - 'basic-service/**'  
    branches:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.4

    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./basic-service
        tags: sharadregoti/basic-service:${{steps.branch-name.outputs.current_branch}}
        file: ./basic-service/Dockerfile

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: "Application can be accessed at this url: http://${{steps.branch-name.outputs.current_branch}}3.7.100.88.sslip.io:4080"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: 'Deploy'
    #   uses: 'deliverybot/helm@v1'
    #   with:
    #     release: 'basic-service'
    #     namespace: 'default'
    #     chart: 'app'
    #     token: '${{ github.token }}'
    #     values: |
    #       branch_name: foobar
    #   env:
    #     KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'

    # - uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: apply -f basic-service/deployment.yaml
